# Generated by Django 4.1.7 on 2023-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regisration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=20)),
            ],
        ),
    ]
