# Generated by Django 4.1.7 on 2023-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='Mobile_Number',
            field=models.IntegerField(),
        ),
    ]
