# Generated by Django 4.1.7 on 2023-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0002_alter_regisration_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('Course', models.IntegerField()),
            ],
        ),
    ]
