# Generated by Django 4.1.7 on 2023-06-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0004_alter_enquiry_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regisration',
            old_name='Mobile_Number',
            new_name='Number',
        ),
    ]
